version: 1.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
hooks:
# BeforeInstall:
#    - location: scripts/install_dependencies.sh
#     timeout: 300
#      runas: root
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#      timeout: 300
#      runas: root
  ApplicationStart:
    - location: /home/ubuntu/scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /home/ubuntu/scripts/stop_server.sh
      timeout: 300
      runas: root